In [ ]:
import torch
import torch.nn as nn

#Simple neural network with single perceptron

In [ ]:
class Model(nn.Module):   # interiting the nn.Module
  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [ ]:
# creating dataset
features = torch.rand(10,5)

# creating model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.4644],
        [0.4685],
        [0.5127],
        [0.5810],
        [0.5866],
        [0.4973],
        [0.5854],
        [0.5664],
        [0.5505],
        [0.4984]], grad_fn=<SigmoidBackward0>)

In [ ]:
# displaying model weights and bias
model.linear.weight

Parameter containing:
tensor([[-0.3555,  0.0570,  0.3563, -0.0676, -0.1914]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([0.2805], requires_grad=True)

**visualizing the network**

In [ ]:
! pip install torchinfo

In [ ]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

#Building Multi-Layered neural network

In [ ]:
# nn
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()

    # instead of writting like this

    #self.linear1 = nn.Linear(num_features,3)
    #self.relu = nn.ReLU()
    #self.linear2 = nn.Linear(3,1)
    #self.sigmoid = nn.Sigmoid()

    # we can use sequential container

    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    #out = self.linear1(features)
    #out = self.relu(out)
    #out = self.linear2(out)
    #out = self.sigmoid(out)

    out = self.network(features)

    return out

In [ ]:
model = Model(features.shape[1])
model(features)

tensor([[0.5604],
        [0.5611],
        [0.5604],
        [0.5517],
        [0.5618],
        [0.5548],
        [0.5630],
        [0.5633],
        [0.5608],
        [0.5604]], grad_fn=<SigmoidBackward0>)

In [ ]:
# displaying weight
model.linear1.weight

Parameter containing:
tensor([[ 0.2119,  0.1781, -0.4110, -0.3778,  0.0632],
        [ 0.2659, -0.3895,  0.1225, -0.2961,  0.0170],
        [ 0.0101,  0.0723,  0.0241, -0.4120, -0.0615]], requires_grad=True)

In [ ]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00